export const customers = [
    {
        customerName: 'Jane Cooper',
        company: 'Microsoft',
        phoneNumber: '(225) 555-0118',
        email: 'jane@microsoft.com',
        country: 'United States',
        status: true,
    },
    {
        customerName: 'Floyd Miles',
        company: 'Yahoo',
        phoneNumber: '(205) 555-0100',
        email: 'floyd@yahoo.com',
        country: 'Kiribati',
        status: false,
    },
    {
        customerName: 'Ronald Richards',
        company: 'Adobe',
        phoneNumber: '(302) 555-0107',
        email: 'ronald@adobe.com',
        country: 'Israel',
        status: false,
    },
    {
        customerName: 'Marvin McKinney',
        company: 'Tesla',
        phoneNumber: '(252) 555-0126',
        email: 'marvin@tesla.com',
        country: 'Iran',
        status: true,
    },
    {
        customerName: 'Jerome Bell',
        company: 'Google',
        phoneNumber: '(629) 555-0129',
        email: 'jerome@google.com',
        country: 'Réunion',
        status: true,
    },
    {
        customerName: 'Kathryn Murphy',
        company: 'Microsoft',
        phoneNumber: '(406) 555-0120',
        email: 'kathryn@microsoft.com',
        country: 'Curaçao',
        status: true,
    },
    {
        customerName: 'Jacob Jones',
        company: 'Yahoo',
        phoneNumber: '(208) 555-0112',
        email: 'jacob@yahoo.com',
        country: 'Brazil',
        status: true,
    },
    {
        customerName: 'Kristin Watson',
        company: 'Facebook',
        phoneNumber: '(704) 555-0127',
        email: 'kristin@facebook.com',
        country: 'Åland Islands',
        status: false,
    },
    {
        customerName: 'Paul Hayes',
        company: 'Amazon',
        phoneNumber: '(507) 555-0142',
        email: 'paul@amazon.com',
        country: 'Canada',
        status: true,
    },
    {
        customerName: 'Emma Walker',
        company: 'Netflix',
        phoneNumber: '(318) 555-0134',
        email: 'emma@netflix.com',
        country: 'Australia',
        status: false,
    },
    {
        customerName: 'Liam Scott',
        company: 'Spotify',
        phoneNumber: '(620) 555-0198',
        email: 'liam@spotify.com',
        country: 'New Zealand',
        status: true,
    },
    {
        customerName: 'Olivia Davis',
        company: 'Apple',
        phoneNumber: '(415) 555-0173',
        email: 'olivia@apple.com',
        country: 'United Kingdom',
        status: true,
    },
    {
        customerName: 'Noah Martinez',
        company: 'IBM',
        phoneNumber: '(214) 555-0161',
        email: 'noah@ibm.com',
        country: 'Mexico',
        status: false,
    },
    {
        customerName: 'Sophia Brown',
        company: 'Twitter',
        phoneNumber: '(517) 555-0185',
        email: 'sophia@twitter.com',
        country: 'Germany',
        status: true,
    },
    {
        customerName: 'Mason Wilson',
        company: 'LinkedIn',
        phoneNumber: '(719) 555-0194',
        email: 'mason@linkedin.com',
        country: 'France',
        status: false,
    },
    {
        customerName: 'Ava Moore',
        company: 'Salesforce',
        phoneNumber: '(619) 555-0119',
        email: 'ava@salesforce.com',
        country: 'Italy',
        status: true,
    },
    {
        customerName: 'Elijah Thompson',
        company: 'Oracle',
        phoneNumber: '(405) 555-0152',
        email: 'elijah@oracle.com',
        country: 'Spain',
        status: true,
    },
    {
        customerName: 'Isabella Lee',
        company: 'Cisco',
        phoneNumber: '(213) 555-0177',
        email: 'isabella@cisco.com',
        country: 'Netherlands',
        status: false,
    },
    {
        customerName: 'James Harris',
        company: 'SAP',
        phoneNumber: '(518) 555-0193',
        email: 'james@sap.com',
        country: 'Sweden',
        status: true,
    },
    {
        customerName: 'Mia Clark',
        company: 'Uber',
        phoneNumber: '(816) 555-0121',
        email: 'mia@uber.com',
        country: 'Japan',
        status: true,
    },
    {
        customerName: 'Lucas Lewis',
        company: 'Pinterest',
        phoneNumber: '(202) 555-0182',
        email: 'lucas@pinterest.com',
        country: 'South Korea',
        status: false,
    },
    {
        customerName: 'Amelia Young',
        company: 'Adobe',
        phoneNumber: '(719) 555-0148',
        email: 'amelia@adobe.com',
        country: 'Switzerland',
        status: true,
    },
    {
        customerName: 'Henry Allen',
        company: 'Slack',
        phoneNumber: '(213) 555-0197',
        email: 'henry@slack.com',
        country: 'Ireland',
        status: true,
    },
    {
        customerName: 'Evelyn King',
        company: 'Zoom',
        phoneNumber: '(302) 555-0169',
        email: 'evelyn@zoom.com',
        country: 'Norway',
        status: false,
    },
    {
        customerName: 'Alexander Scott',
        company: 'Shopify',
        phoneNumber: '(415) 555-0187',
        email: 'alexander@shopify.com',
        country: 'Finland',
        status: true,
    },
    {
        customerName: 'Charlotte Green',
        company: 'Twitch',
        phoneNumber: '(507) 555-0125',
        email: 'charlotte@twitch.com',
        country: 'Denmark',
        status: true,
    },
    {
        customerName: 'Sebastian Baker',
        company: 'Square',
        phoneNumber: '(318) 555-0196',
        email: 'sebastian@square.com',
        country: 'Belgium',
        status: false,
    },
    {
        customerName: 'Harper Martinez',
        company: 'TikTok',
        phoneNumber: '(619) 555-0188',
        email: 'harper@tiktok.com',
        country: 'Austria',
        status: true,
    },
    {
        customerName: 'Daniel Rodriguez',
        company: 'Paypal',
        phoneNumber: '(720) 555-0150',
        email: 'daniel@paypal.com',
        country: 'Portugal',
        status: true,
    },
    {
        customerName: 'Aria Perez',
        company: 'Stripe',
        phoneNumber: '(313) 555-0171',
        email: 'aria@stripe.com',
        country: 'Poland',
        status: false,
    },
    {
        customerName: 'William Hall',
        company: 'Squarespace',
        phoneNumber: '(414) 555-0139',
        email: 'william@squarespace.com',
        country: 'Greece',
        status: true,
    },
    {
        customerName: 'Sofia Lopez',
        company: 'Zendesk',
        phoneNumber: '(615) 555-0141',
        email: 'sofia@zendesk.com',
        country: 'Czech Republic',
        status: true,
    },
    {
        customerName: 'Oliver Nelson',
        company: 'Dropbox',
        phoneNumber: '(517) 555-0190',
        email: 'oliver@dropbox.com',
        country: 'Hungary',
        status: false,
    },
];
